# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.models.activate_terminal_event_request import ActivateTerminalEventRequest

class TestActivateTerminalEventRequest(unittest.TestCase):
    """ActivateTerminalEventRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivateTerminalEventRequest:
        """Test ActivateTerminalEventRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivateTerminalEventRequest`
        """
        model = ActivateTerminalEventRequest()
        if include_optional:
            return ActivateTerminalEventRequest(
                event_name = 'eventName',
                effective_date = '2024-04-29T12:03:44Z',
                instances = 56,
                unlimited_instances = True
            )
        else:
            return ActivateTerminalEventRequest(
                event_name = 'eventName',
        )
        """

    def testActivateTerminalEventRequest(self):
        """Test ActivateTerminalEventRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
