# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.get_list_of_device_subscription_details_for_given_account_api import GetListOfDeviceSubscriptionDetailsForGivenAccountApi


class TestGetListOfDeviceSubscriptionDetailsForGivenAccountApi(unittest.TestCase):
    """GetListOfDeviceSubscriptionDetailsForGivenAccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetListOfDeviceSubscriptionDetailsForGivenAccountApi()

    def tearDown(self) -> None:
        pass

    def test_get_acct_device_response(self) -> None:
        """Test case for get_acct_device_response

        Return list of Device Subscription Details for given account.
        """
        pass


if __name__ == '__main__':
    unittest.main()
