# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.get_device_location_history_api import GetDeviceLocationHistoryApi


class TestGetDeviceLocationHistoryApi(unittest.TestCase):
    """GetDeviceLocationHistoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetDeviceLocationHistoryApi()

    def tearDown(self) -> None:
        pass

    def test_get_device_location_history(self) -> None:
        """Test case for get_device_location_history

        Get Device Location History during a specified time frame.
        """
        pass


if __name__ == '__main__':
    unittest.main()
