# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.search_devices_api import SearchDevicesApi


class TestSearchDevicesApi(unittest.TestCase):
    """SearchDevicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchDevicesApi()

    def tearDown(self) -> None:
        pass

    def test_search_devices(self) -> None:
        """Test case for search_devices

        Search for devices based on various filters.
        """
        pass


if __name__ == '__main__':
    unittest.main()
