# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.customers_api import CustomersApi


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomersApi()

    def tearDown(self) -> None:
        pass

    def test_create_customer(self) -> None:
        """Test case for create_customer

        Creates a customer
        """
        pass

    def test_get_customer_details(self) -> None:
        """Test case for get_customer_details

        Get details for a given customerId
        """
        pass

    def test_update_customer(self) -> None:
        """Test case for update_customer

        Edits a customer
        """
        pass


if __name__ == '__main__':
    unittest.main()
