# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        Create user.
        """
        pass

    def test_delete_user_by_id(self) -> None:
        """Test case for delete_user_by_id

        Delete user for a given userId
        """
        pass

    def test_get_all_users(self) -> None:
        """Test case for get_all_users

        Get all users based on the authority of the user invoking this API
        """
        pass

    def test_get_user_by_id(self) -> None:
        """Test case for get_user_by_id

        Get user details for a given userId
        """
        pass

    def test_reset_user_password(self) -> None:
        """Test case for reset_user_password

        Reset password for the given user
        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        Update user
        """
        pass


if __name__ == '__main__':
    unittest.main()
