# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.get_event_rate_plans_assigned_to_device_api import GetEventRatePlansAssignedToDeviceApi


class TestGetEventRatePlansAssignedToDeviceApi(unittest.TestCase):
    """GetEventRatePlansAssignedToDeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetEventRatePlansAssignedToDeviceApi()

    def tearDown(self) -> None:
        pass

    def test_get_terminal_events(self) -> None:
        """Test case for get_terminal_events

        List of currently active and future-dated event plans for device.
        """
        pass


if __name__ == '__main__':
    unittest.main()
