# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.edit_device_api import EditDeviceApi


class TestEditDeviceApi(unittest.TestCase):
    """EditDeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EditDeviceApi()

    def tearDown(self) -> None:
        pass

    def test_edit_device(self) -> None:
        """Test case for edit_device

        Modify any device attributes such as Status, Rate Plan, Communication Plan, Custom Fields and other identifiers.
        """
        pass


if __name__ == '__main__':
    unittest.main()
