# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.models.send_sms_messages_request import SendSmsMessagesRequest

class TestSendSmsMessagesRequest(unittest.TestCase):
    """SendSmsMessagesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendSmsMessagesRequest:
        """Test SendSmsMessagesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendSmsMessagesRequest`
        """
        model = SendSmsMessagesRequest()
        if include_optional:
            return SendSmsMessagesRequest(
                message_text = '',
                message_encoding = '',
                data_coding = 56,
                tpvp = 56,
                callback_param = jasperclient.models.send_sms_messages_request_callback_param.SendSmsMessagesRequest_callbackParam(
                    callback_type = '', 
                    callback_url = '', )
            )
        else:
            return SendSmsMessagesRequest(
        )
        """

    def testSendSmsMessagesRequest(self):
        """Test SendSmsMessagesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
