# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.models.customer_dto import CustomerDTO

class TestCustomerDTO(unittest.TestCase):
    """CustomerDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerDTO:
        """Test CustomerDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerDTO`
        """
        model = CustomerDTO()
        if include_optional:
            return CustomerDTO(
                name = 'l0',
                account_name = '',
                security_question = 'l0123456789',
                security_answer = '',
                ship_to_bill_address = True,
                contacts = [
                    null
                    ],
                billing_address = jasperclient.models.customer_dto_billing_address.CustomerDTO_billingAddress(
                    address_line1 = '', 
                    address_line2 = '', 
                    city = '', 
                    state = '', 
                    country = '', 
                    postal_code = '', ),
                shipping_address = jasperclient.models.customer_dto_billing_address.CustomerDTO_billingAddress(
                    address_line1 = '', 
                    address_line2 = '', 
                    city = '', 
                    state = '', 
                    country = '', 
                    postal_code = '', )
            )
        else:
            return CustomerDTO(
        )
        """

    def testCustomerDTO(self):
        """Test CustomerDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
