# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.get_device_audit_trails_api import GetDeviceAuditTrailsApi


class TestGetDeviceAuditTrailsApi(unittest.TestCase):
    """GetDeviceAuditTrailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetDeviceAuditTrailsApi()

    def tearDown(self) -> None:
        pass

    def test_get_device_audit_trails(self) -> None:
        """Test case for get_device_audit_trails

        Retrieve audit history for a device based on various filters.
        """
        pass


if __name__ == '__main__':
    unittest.main()
