# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.assign_event_rate_plan_to_device_api import AssignEventRatePlanToDeviceApi


class TestAssignEventRatePlanToDeviceApi(unittest.TestCase):
    """AssignEventRatePlanToDeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssignEventRatePlanToDeviceApi()

    def tearDown(self) -> None:
        pass

    def test_activate_terminal_event(self) -> None:
        """Test case for activate_terminal_event

        Triggers activation of an event for a device on the effective date
        """
        pass


if __name__ == '__main__':
    unittest.main()
