# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.models.user_update_dto import UserUpdateDTO

class TestUserUpdateDTO(unittest.TestCase):
    """UserUpdateDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUpdateDTO:
        """Test UserUpdateDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUpdateDTO`
        """
        model = UserUpdateDTO()
        if include_optional:
            return UserUpdateDTO(
                role_name = '',
                access_type = '',
                user_locked = True,
                first_name = '0',
                last_name = '0',
                email = 'W@9LCSLv1C1ylmgd0.Y2TA5TkIRHRRA401iz1CiIy012',
                phone = '',
                language = '',
                time_zone = '',
                live_update_enabled = True
            )
        else:
            return UserUpdateDTO(
        )
        """

    def testUserUpdateDTO(self):
        """Test UserUpdateDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
