# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.edit_event_rate_plans_assigned_to_device_api import EditEventRatePlansAssignedToDeviceApi


class TestEditEventRatePlansAssignedToDeviceApi(unittest.TestCase):
    """EditEventRatePlansAssignedToDeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EditEventRatePlansAssignedToDeviceApi()

    def tearDown(self) -> None:
        pass

    def test_edit_event_instances(self) -> None:
        """Test case for edit_event_instances

        Cancel Pending Events for device
        """
        pass


if __name__ == '__main__':
    unittest.main()
