# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.models.customer_dto_billing_address import CustomerDTOBillingAddress

class TestCustomerDTOBillingAddress(unittest.TestCase):
    """CustomerDTOBillingAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerDTOBillingAddress:
        """Test CustomerDTOBillingAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerDTOBillingAddress`
        """
        model = CustomerDTOBillingAddress()
        if include_optional:
            return CustomerDTOBillingAddress(
                address_line1 = '',
                address_line2 = '',
                city = '',
                state = '',
                country = '',
                postal_code = ''
            )
        else:
            return CustomerDTOBillingAddress(
        )
        """

    def testCustomerDTOBillingAddress(self):
        """Test CustomerDTOBillingAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
