# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.get_list_of_topk_usage_details_group_by_carrier_country_rate_plan_rating_zone_for_given_account_api import GetListOfTOPKUsageDetailsGroupByCarrierCountryRatePlanRatingZoneForGivenAccountApi


class TestGetListOfTOPKUsageDetailsGroupByCarrierCountryRatePlanRatingZoneForGivenAccountApi(unittest.TestCase):
    """GetListOfTOPKUsageDetailsGroupByCarrierCountryRatePlanRatingZoneForGivenAccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetListOfTOPKUsageDetailsGroupByCarrierCountryRatePlanRatingZoneForGivenAccountApi()

    def tearDown(self) -> None:
        pass

    def test_get_top_k_usage_by_account(self) -> None:
        """Test case for get_top_k_usage_by_account

        Return list of TOP K Usage Details Group by Carrier, Country, RatePlan, RatingZone for given account.
        """
        pass


if __name__ == '__main__':
    unittest.main()
