# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.get_sms_details_api import GetSMSDetailsApi


class TestGetSMSDetailsApi(unittest.TestCase):
    """GetSMSDetailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetSMSDetailsApi()

    def tearDown(self) -> None:
        pass

    def test_get_sms_message_detail(self) -> None:
        """Test case for get_sms_message_detail

        Returns detailed information about a message.
        """
        pass


if __name__ == '__main__':
    unittest.main()
