# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.api_key_api import APIKeyApi


class TestAPIKeyApi(unittest.TestCase):
    """APIKeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APIKeyApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_key_for_an_user(self) -> None:
        """Test case for get_api_key_for_an_user

        GET API Key for a given user
        """
        pass


if __name__ == '__main__':
    unittest.main()
