# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.get_device_usage_by_zone_api import GetDeviceUsageByZoneApi


class TestGetDeviceUsageByZoneApi(unittest.TestCase):
    """GetDeviceUsageByZoneApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetDeviceUsageByZoneApi()

    def tearDown(self) -> None:
        pass

    def test_get_device_cycle_usage_in_zones(self) -> None:
        """Test case for get_device_cycle_usage_in_zones

        Return usage related details for a device under different zones and rate plans.
        """
        pass


if __name__ == '__main__':
    unittest.main()
