# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.get_device_usage_api import GetDeviceUsageApi


class TestGetDeviceUsageApi(unittest.TestCase):
    """GetDeviceUsageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetDeviceUsageApi()

    def tearDown(self) -> None:
        pass

    def test_get_usages_by_iccid(self) -> None:
        """Test case for get_usages_by_iccid

        Return usage related details for a given device.
        """
        pass


if __name__ == '__main__':
    unittest.main()
