# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.get_session_details_api import GetSessionDetailsApi


class TestGetSessionDetailsApi(unittest.TestCase):
    """GetSessionDetailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetSessionDetailsApi()

    def tearDown(self) -> None:
        pass

    def test_get_session_info_by_iccid(self) -> None:
        """Test case for get_session_info_by_iccid

        Return information related to the current or most recent session.
        """
        pass


if __name__ == '__main__':
    unittest.main()
