# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.echo_api import EchoApi


class TestEchoApi(unittest.TestCase):
    """EchoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EchoApi()

    def tearDown(self) -> None:
        pass

    def test_get_msg(self) -> None:
        """Test case for get_msg

        Simply returns a parameter passed by the client.
        """
        pass


if __name__ == '__main__':
    unittest.main()
