# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.search_sms_api import SearchSMSApi


class TestSearchSMSApi(unittest.TestCase):
    """SearchSMSApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchSMSApi()

    def tearDown(self) -> None:
        pass

    def test_get_sms_messages(self) -> None:
        """Test case for get_sms_messages

        Search for messages that have been sent or received during a specified time frame.
        """
        pass


if __name__ == '__main__':
    unittest.main()
