# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.get_usage_by_rate_plan_api import GetUsageByRatePlanApi


class TestGetUsageByRatePlanApi(unittest.TestCase):
    """GetUsageByRatePlanApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetUsageByRatePlanApi()

    def tearDown(self) -> None:
        pass

    def test_get_usage_by_rate_plan(self) -> None:
        """Test case for get_usage_by_rate_plan

        Get Usage by RatePlan
        """
        pass


if __name__ == '__main__':
    unittest.main()
