# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.api.send_sms_api import SendSMSApi


class TestSendSMSApi(unittest.TestCase):
    """SendSMSApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SendSMSApi()

    def tearDown(self) -> None:
        pass

    def test_send_sms_messages(self) -> None:
        """Test case for send_sms_messages

        Send SMS message to a device.
        """
        pass


if __name__ == '__main__':
    unittest.main()
