# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jasperclient.models.edit_event_instances_request import EditEventInstancesRequest

class TestEditEventInstancesRequest(unittest.TestCase):
    """EditEventInstancesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditEventInstancesRequest:
        """Test EditEventInstancesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditEventInstancesRequest`
        """
        model = EditEventInstancesRequest()
        if include_optional:
            return EditEventInstancesRequest(
                event_id = '123456',
                event_name = 'eventName',
                action = 'CancelPendingEvents'
            )
        else:
            return EditEventInstancesRequest(
                action = 'CancelPendingEvents',
        )
        """

    def testEditEventInstancesRequest(self):
        """Test EditEventInstancesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
