# coding: utf-8

"""
Cisco IoT Control Center API

A Python client for the Cisco IoT Control Center (Jasper) REST API.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated

from jasperclient.api_client import ApiClient, RequestSerialized
from jasperclient.api_response import ApiResponse
from jasperclient.rest import RESTResponseType


class GetDeviceUsageByZoneApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def get_device_cycle_usage_in_zones(
        self,
        iccid: Annotated[StrictStr, Field(description="ICCID")],
        api_version: Annotated[StrictStr, Field(description="Defaults to 1")],
        cycle_start_date: Annotated[
            Optional[StrictStr],
            Field(
                description="Filter by start date of a billing cycle.</br> The format is yyyy-MM-ddZ </br> Eg: 2016-11-10Z or 2016-11-10+00:00"
            ),
        ] = None,
        rate_plan: Annotated[
            Optional[StrictStr], Field(description="Filter by rate plan")
        ] = None,
        zone: Annotated[
            Optional[StrictStr], Field(description="Filter by zone")
        ] = None,
        is_active_rate_plan: Annotated[
            Optional[StrictStr], Field(description="Filter by active rate plans")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Return usage related details for a device under different zones and rate plans.



        :param iccid: ICCID (required)
        :type iccid: str
        :param api_version: Defaults to 1 (required)
        :type api_version: str
        :param cycle_start_date: Filter by start date of a billing cycle.</br> The format is yyyy-MM-ddZ </br> Eg: 2016-11-10Z or 2016-11-10+00:00
        :type cycle_start_date: str
        :param rate_plan: Filter by rate plan
        :type rate_plan: str
        :param zone: Filter by zone
        :type zone: str
        :param is_active_rate_plan: Filter by active rate plans
        :type is_active_rate_plan: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_device_cycle_usage_in_zones_serialize(
            iccid=iccid,
            api_version=api_version,
            cycle_start_date=cycle_start_date,
            rate_plan=rate_plan,
            zone=zone,
            is_active_rate_plan=is_active_rate_plan,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": None,
            "400": None,
            "401": None,
            "404": None,
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def get_device_cycle_usage_in_zones_with_http_info(
        self,
        iccid: Annotated[StrictStr, Field(description="ICCID")],
        api_version: Annotated[StrictStr, Field(description="Defaults to 1")],
        cycle_start_date: Annotated[
            Optional[StrictStr],
            Field(
                description="Filter by start date of a billing cycle.</br> The format is yyyy-MM-ddZ </br> Eg: 2016-11-10Z or 2016-11-10+00:00"
            ),
        ] = None,
        rate_plan: Annotated[
            Optional[StrictStr], Field(description="Filter by rate plan")
        ] = None,
        zone: Annotated[
            Optional[StrictStr], Field(description="Filter by zone")
        ] = None,
        is_active_rate_plan: Annotated[
            Optional[StrictStr], Field(description="Filter by active rate plans")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Return usage related details for a device under different zones and rate plans.



        :param iccid: ICCID (required)
        :type iccid: str
        :param api_version: Defaults to 1 (required)
        :type api_version: str
        :param cycle_start_date: Filter by start date of a billing cycle.</br> The format is yyyy-MM-ddZ </br> Eg: 2016-11-10Z or 2016-11-10+00:00
        :type cycle_start_date: str
        :param rate_plan: Filter by rate plan
        :type rate_plan: str
        :param zone: Filter by zone
        :type zone: str
        :param is_active_rate_plan: Filter by active rate plans
        :type is_active_rate_plan: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_device_cycle_usage_in_zones_serialize(
            iccid=iccid,
            api_version=api_version,
            cycle_start_date=cycle_start_date,
            rate_plan=rate_plan,
            zone=zone,
            is_active_rate_plan=is_active_rate_plan,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": None,
            "400": None,
            "401": None,
            "404": None,
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def get_device_cycle_usage_in_zones_without_preload_content(
        self,
        iccid: Annotated[StrictStr, Field(description="ICCID")],
        api_version: Annotated[StrictStr, Field(description="Defaults to 1")],
        cycle_start_date: Annotated[
            Optional[StrictStr],
            Field(
                description="Filter by start date of a billing cycle.</br> The format is yyyy-MM-ddZ </br> Eg: 2016-11-10Z or 2016-11-10+00:00"
            ),
        ] = None,
        rate_plan: Annotated[
            Optional[StrictStr], Field(description="Filter by rate plan")
        ] = None,
        zone: Annotated[
            Optional[StrictStr], Field(description="Filter by zone")
        ] = None,
        is_active_rate_plan: Annotated[
            Optional[StrictStr], Field(description="Filter by active rate plans")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Return usage related details for a device under different zones and rate plans.



        :param iccid: ICCID (required)
        :type iccid: str
        :param api_version: Defaults to 1 (required)
        :type api_version: str
        :param cycle_start_date: Filter by start date of a billing cycle.</br> The format is yyyy-MM-ddZ </br> Eg: 2016-11-10Z or 2016-11-10+00:00
        :type cycle_start_date: str
        :param rate_plan: Filter by rate plan
        :type rate_plan: str
        :param zone: Filter by zone
        :type zone: str
        :param is_active_rate_plan: Filter by active rate plans
        :type is_active_rate_plan: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_device_cycle_usage_in_zones_serialize(
            iccid=iccid,
            api_version=api_version,
            cycle_start_date=cycle_start_date,
            rate_plan=rate_plan,
            zone=zone,
            is_active_rate_plan=is_active_rate_plan,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": None,
            "400": None,
            "401": None,
            "404": None,
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _get_device_cycle_usage_in_zones_serialize(
        self,
        iccid,
        api_version,
        cycle_start_date,
        rate_plan,
        zone,
        is_active_rate_plan,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if iccid is not None:
            _path_params["iccid"] = iccid
        if api_version is not None:
            _path_params["apiVersion"] = api_version
        # process the query parameters
        if cycle_start_date is not None:

            _query_params.append(("cycleStartDate", cycle_start_date))

        if rate_plan is not None:

            _query_params.append(("ratePlan", rate_plan))

        if zone is not None:

            _query_params.append(("zone", zone))

        if is_active_rate_plan is not None:

            _query_params.append(("isActiveRatePlan", is_active_rate_plan))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # authentication setting
        _auth_settings: List[str] = ["basicAuth"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/v{apiVersion}/devices/{iccid}/usageInZone",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
