# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated

from jasperclient.api_client import ApiClient, RequestSerialized
from jasperclient.api_response import ApiResponse
from jasperclient.rest import RESTResponseType


class SearchDevicesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def search_devices(
        self,
        api_version: Annotated[StrictStr, Field(description="Defaults to 1")],
        modified_since: Annotated[StrictStr, Field(description="Filter by time since last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-04-18T17:31:34+00:00")],
        account_id: Annotated[Optional[StrictInt], Field(description="Filter by account")] = None,
        modified_till: Annotated[Optional[StrictStr], Field(description="Filter by time till last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-05-18T17:31:34+00:00")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by device status")] = None,
        account_custom1: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 1")] = None,
        account_custom2: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 2")] = None,
        account_custom3: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 3")] = None,
        account_custom4: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 4")] = None,
        account_custom5: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 5")] = None,
        account_custom6: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 6")] = None,
        account_custom7: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 7")] = None,
        account_custom8: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 8")] = None,
        account_custom9: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 9")] = None,
        account_custom10: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 10")] = None,
        operator_custom1: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 1")] = None,
        operator_custom2: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 2")] = None,
        operator_custom3: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 3")] = None,
        operator_custom4: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 4")] = None,
        operator_custom5: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 5")] = None,
        customer_custom1: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 1")] = None,
        customer_custom2: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 2")] = None,
        customer_custom3: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 3")] = None,
        customer_custom4: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 4")] = None,
        customer_custom5: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 5")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="Maximum of 50, defaults to 50")] = None,
        page_number: Annotated[Optional[StrictInt], Field(description="Defaults to 1")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Search for devices based on various filters.

        

        :param api_version: Defaults to 1 (required)
        :type api_version: str
        :param modified_since: Filter by time since last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-04-18T17:31:34+00:00 (required)
        :type modified_since: str
        :param account_id: Filter by account
        :type account_id: int
        :param modified_till: Filter by time till last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-05-18T17:31:34+00:00
        :type modified_till: str
        :param status: Filter by device status
        :type status: str
        :param account_custom1: Filter by account custom field 1
        :type account_custom1: str
        :param account_custom2: Filter by account custom field 2
        :type account_custom2: str
        :param account_custom3: Filter by account custom field 3
        :type account_custom3: str
        :param account_custom4: Filter by account custom field 4
        :type account_custom4: str
        :param account_custom5: Filter by account custom field 5
        :type account_custom5: str
        :param account_custom6: Filter by account custom field 6
        :type account_custom6: str
        :param account_custom7: Filter by account custom field 7
        :type account_custom7: str
        :param account_custom8: Filter by account custom field 8
        :type account_custom8: str
        :param account_custom9: Filter by account custom field 9
        :type account_custom9: str
        :param account_custom10: Filter by account custom field 10
        :type account_custom10: str
        :param operator_custom1: Filter by operator custom field 1
        :type operator_custom1: str
        :param operator_custom2: Filter by operator custom field 2
        :type operator_custom2: str
        :param operator_custom3: Filter by operator custom field 3
        :type operator_custom3: str
        :param operator_custom4: Filter by operator custom field 4
        :type operator_custom4: str
        :param operator_custom5: Filter by operator custom field 5
        :type operator_custom5: str
        :param customer_custom1: Filter by customer custom field 1
        :type customer_custom1: str
        :param customer_custom2: Filter by customer custom field 2
        :type customer_custom2: str
        :param customer_custom3: Filter by customer custom field 3
        :type customer_custom3: str
        :param customer_custom4: Filter by customer custom field 4
        :type customer_custom4: str
        :param customer_custom5: Filter by customer custom field 5
        :type customer_custom5: str
        :param page_size: Maximum of 50, defaults to 50
        :type page_size: int
        :param page_number: Defaults to 1
        :type page_number: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_devices_serialize(
            api_version=api_version,
            modified_since=modified_since,
            account_id=account_id,
            modified_till=modified_till,
            status=status,
            account_custom1=account_custom1,
            account_custom2=account_custom2,
            account_custom3=account_custom3,
            account_custom4=account_custom4,
            account_custom5=account_custom5,
            account_custom6=account_custom6,
            account_custom7=account_custom7,
            account_custom8=account_custom8,
            account_custom9=account_custom9,
            account_custom10=account_custom10,
            operator_custom1=operator_custom1,
            operator_custom2=operator_custom2,
            operator_custom3=operator_custom3,
            operator_custom4=operator_custom4,
            operator_custom5=operator_custom5,
            customer_custom1=customer_custom1,
            customer_custom2=customer_custom2,
            customer_custom3=customer_custom3,
            customer_custom4=customer_custom4,
            customer_custom5=customer_custom5,
            page_size=page_size,
            page_number=page_number,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '400': None,
            '401': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def search_devices_with_http_info(
        self,
        api_version: Annotated[StrictStr, Field(description="Defaults to 1")],
        modified_since: Annotated[StrictStr, Field(description="Filter by time since last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-04-18T17:31:34+00:00")],
        account_id: Annotated[Optional[StrictInt], Field(description="Filter by account")] = None,
        modified_till: Annotated[Optional[StrictStr], Field(description="Filter by time till last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-05-18T17:31:34+00:00")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by device status")] = None,
        account_custom1: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 1")] = None,
        account_custom2: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 2")] = None,
        account_custom3: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 3")] = None,
        account_custom4: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 4")] = None,
        account_custom5: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 5")] = None,
        account_custom6: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 6")] = None,
        account_custom7: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 7")] = None,
        account_custom8: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 8")] = None,
        account_custom9: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 9")] = None,
        account_custom10: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 10")] = None,
        operator_custom1: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 1")] = None,
        operator_custom2: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 2")] = None,
        operator_custom3: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 3")] = None,
        operator_custom4: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 4")] = None,
        operator_custom5: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 5")] = None,
        customer_custom1: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 1")] = None,
        customer_custom2: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 2")] = None,
        customer_custom3: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 3")] = None,
        customer_custom4: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 4")] = None,
        customer_custom5: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 5")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="Maximum of 50, defaults to 50")] = None,
        page_number: Annotated[Optional[StrictInt], Field(description="Defaults to 1")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Search for devices based on various filters.

        

        :param api_version: Defaults to 1 (required)
        :type api_version: str
        :param modified_since: Filter by time since last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-04-18T17:31:34+00:00 (required)
        :type modified_since: str
        :param account_id: Filter by account
        :type account_id: int
        :param modified_till: Filter by time till last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-05-18T17:31:34+00:00
        :type modified_till: str
        :param status: Filter by device status
        :type status: str
        :param account_custom1: Filter by account custom field 1
        :type account_custom1: str
        :param account_custom2: Filter by account custom field 2
        :type account_custom2: str
        :param account_custom3: Filter by account custom field 3
        :type account_custom3: str
        :param account_custom4: Filter by account custom field 4
        :type account_custom4: str
        :param account_custom5: Filter by account custom field 5
        :type account_custom5: str
        :param account_custom6: Filter by account custom field 6
        :type account_custom6: str
        :param account_custom7: Filter by account custom field 7
        :type account_custom7: str
        :param account_custom8: Filter by account custom field 8
        :type account_custom8: str
        :param account_custom9: Filter by account custom field 9
        :type account_custom9: str
        :param account_custom10: Filter by account custom field 10
        :type account_custom10: str
        :param operator_custom1: Filter by operator custom field 1
        :type operator_custom1: str
        :param operator_custom2: Filter by operator custom field 2
        :type operator_custom2: str
        :param operator_custom3: Filter by operator custom field 3
        :type operator_custom3: str
        :param operator_custom4: Filter by operator custom field 4
        :type operator_custom4: str
        :param operator_custom5: Filter by operator custom field 5
        :type operator_custom5: str
        :param customer_custom1: Filter by customer custom field 1
        :type customer_custom1: str
        :param customer_custom2: Filter by customer custom field 2
        :type customer_custom2: str
        :param customer_custom3: Filter by customer custom field 3
        :type customer_custom3: str
        :param customer_custom4: Filter by customer custom field 4
        :type customer_custom4: str
        :param customer_custom5: Filter by customer custom field 5
        :type customer_custom5: str
        :param page_size: Maximum of 50, defaults to 50
        :type page_size: int
        :param page_number: Defaults to 1
        :type page_number: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_devices_serialize(
            api_version=api_version,
            modified_since=modified_since,
            account_id=account_id,
            modified_till=modified_till,
            status=status,
            account_custom1=account_custom1,
            account_custom2=account_custom2,
            account_custom3=account_custom3,
            account_custom4=account_custom4,
            account_custom5=account_custom5,
            account_custom6=account_custom6,
            account_custom7=account_custom7,
            account_custom8=account_custom8,
            account_custom9=account_custom9,
            account_custom10=account_custom10,
            operator_custom1=operator_custom1,
            operator_custom2=operator_custom2,
            operator_custom3=operator_custom3,
            operator_custom4=operator_custom4,
            operator_custom5=operator_custom5,
            customer_custom1=customer_custom1,
            customer_custom2=customer_custom2,
            customer_custom3=customer_custom3,
            customer_custom4=customer_custom4,
            customer_custom5=customer_custom5,
            page_size=page_size,
            page_number=page_number,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '400': None,
            '401': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def search_devices_without_preload_content(
        self,
        api_version: Annotated[StrictStr, Field(description="Defaults to 1")],
        modified_since: Annotated[StrictStr, Field(description="Filter by time since last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-04-18T17:31:34+00:00")],
        account_id: Annotated[Optional[StrictInt], Field(description="Filter by account")] = None,
        modified_till: Annotated[Optional[StrictStr], Field(description="Filter by time till last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-05-18T17:31:34+00:00")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by device status")] = None,
        account_custom1: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 1")] = None,
        account_custom2: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 2")] = None,
        account_custom3: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 3")] = None,
        account_custom4: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 4")] = None,
        account_custom5: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 5")] = None,
        account_custom6: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 6")] = None,
        account_custom7: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 7")] = None,
        account_custom8: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 8")] = None,
        account_custom9: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 9")] = None,
        account_custom10: Annotated[Optional[StrictStr], Field(description="Filter by account custom field 10")] = None,
        operator_custom1: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 1")] = None,
        operator_custom2: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 2")] = None,
        operator_custom3: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 3")] = None,
        operator_custom4: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 4")] = None,
        operator_custom5: Annotated[Optional[StrictStr], Field(description="Filter by operator custom field 5")] = None,
        customer_custom1: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 1")] = None,
        customer_custom2: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 2")] = None,
        customer_custom3: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 3")] = None,
        customer_custom4: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 4")] = None,
        customer_custom5: Annotated[Optional[StrictStr], Field(description="Filter by customer custom field 5")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="Maximum of 50, defaults to 50")] = None,
        page_number: Annotated[Optional[StrictInt], Field(description="Defaults to 1")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Search for devices based on various filters.

        

        :param api_version: Defaults to 1 (required)
        :type api_version: str
        :param modified_since: Filter by time since last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-04-18T17:31:34+00:00 (required)
        :type modified_since: str
        :param account_id: Filter by account
        :type account_id: int
        :param modified_till: Filter by time till last modification was made to device.</br> The format is yyyy-MM-ddTHH:mm:ssZ </br> Eg: 2016-05-18T17:31:34+00:00
        :type modified_till: str
        :param status: Filter by device status
        :type status: str
        :param account_custom1: Filter by account custom field 1
        :type account_custom1: str
        :param account_custom2: Filter by account custom field 2
        :type account_custom2: str
        :param account_custom3: Filter by account custom field 3
        :type account_custom3: str
        :param account_custom4: Filter by account custom field 4
        :type account_custom4: str
        :param account_custom5: Filter by account custom field 5
        :type account_custom5: str
        :param account_custom6: Filter by account custom field 6
        :type account_custom6: str
        :param account_custom7: Filter by account custom field 7
        :type account_custom7: str
        :param account_custom8: Filter by account custom field 8
        :type account_custom8: str
        :param account_custom9: Filter by account custom field 9
        :type account_custom9: str
        :param account_custom10: Filter by account custom field 10
        :type account_custom10: str
        :param operator_custom1: Filter by operator custom field 1
        :type operator_custom1: str
        :param operator_custom2: Filter by operator custom field 2
        :type operator_custom2: str
        :param operator_custom3: Filter by operator custom field 3
        :type operator_custom3: str
        :param operator_custom4: Filter by operator custom field 4
        :type operator_custom4: str
        :param operator_custom5: Filter by operator custom field 5
        :type operator_custom5: str
        :param customer_custom1: Filter by customer custom field 1
        :type customer_custom1: str
        :param customer_custom2: Filter by customer custom field 2
        :type customer_custom2: str
        :param customer_custom3: Filter by customer custom field 3
        :type customer_custom3: str
        :param customer_custom4: Filter by customer custom field 4
        :type customer_custom4: str
        :param customer_custom5: Filter by customer custom field 5
        :type customer_custom5: str
        :param page_size: Maximum of 50, defaults to 50
        :type page_size: int
        :param page_number: Defaults to 1
        :type page_number: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_devices_serialize(
            api_version=api_version,
            modified_since=modified_since,
            account_id=account_id,
            modified_till=modified_till,
            status=status,
            account_custom1=account_custom1,
            account_custom2=account_custom2,
            account_custom3=account_custom3,
            account_custom4=account_custom4,
            account_custom5=account_custom5,
            account_custom6=account_custom6,
            account_custom7=account_custom7,
            account_custom8=account_custom8,
            account_custom9=account_custom9,
            account_custom10=account_custom10,
            operator_custom1=operator_custom1,
            operator_custom2=operator_custom2,
            operator_custom3=operator_custom3,
            operator_custom4=operator_custom4,
            operator_custom5=operator_custom5,
            customer_custom1=customer_custom1,
            customer_custom2=customer_custom2,
            customer_custom3=customer_custom3,
            customer_custom4=customer_custom4,
            customer_custom5=customer_custom5,
            page_size=page_size,
            page_number=page_number,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '400': None,
            '401': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_devices_serialize(
        self,
        api_version,
        modified_since,
        account_id,
        modified_till,
        status,
        account_custom1,
        account_custom2,
        account_custom3,
        account_custom4,
        account_custom5,
        account_custom6,
        account_custom7,
        account_custom8,
        account_custom9,
        account_custom10,
        operator_custom1,
        operator_custom2,
        operator_custom3,
        operator_custom4,
        operator_custom5,
        customer_custom1,
        customer_custom2,
        customer_custom3,
        customer_custom4,
        customer_custom5,
        page_size,
        page_number,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if api_version is not None:
            _path_params['apiVersion'] = api_version
        # process the query parameters
        if account_id is not None:
            
            _query_params.append(('accountId', account_id))
            
        if modified_since is not None:
            
            _query_params.append(('modifiedSince', modified_since))
            
        if modified_till is not None:
            
            _query_params.append(('modifiedTill', modified_till))
            
        if status is not None:
            
            _query_params.append(('status', status))
            
        if account_custom1 is not None:
            
            _query_params.append(('accountCustom1', account_custom1))
            
        if account_custom2 is not None:
            
            _query_params.append(('accountCustom2', account_custom2))
            
        if account_custom3 is not None:
            
            _query_params.append(('accountCustom3', account_custom3))
            
        if account_custom4 is not None:
            
            _query_params.append(('accountCustom4', account_custom4))
            
        if account_custom5 is not None:
            
            _query_params.append(('accountCustom5', account_custom5))
            
        if account_custom6 is not None:
            
            _query_params.append(('accountCustom6', account_custom6))
            
        if account_custom7 is not None:
            
            _query_params.append(('accountCustom7', account_custom7))
            
        if account_custom8 is not None:
            
            _query_params.append(('accountCustom8', account_custom8))
            
        if account_custom9 is not None:
            
            _query_params.append(('accountCustom9', account_custom9))
            
        if account_custom10 is not None:
            
            _query_params.append(('accountCustom10', account_custom10))
            
        if operator_custom1 is not None:
            
            _query_params.append(('operatorCustom1', operator_custom1))
            
        if operator_custom2 is not None:
            
            _query_params.append(('operatorCustom2', operator_custom2))
            
        if operator_custom3 is not None:
            
            _query_params.append(('operatorCustom3', operator_custom3))
            
        if operator_custom4 is not None:
            
            _query_params.append(('operatorCustom4', operator_custom4))
            
        if operator_custom5 is not None:
            
            _query_params.append(('operatorCustom5', operator_custom5))
            
        if customer_custom1 is not None:
            
            _query_params.append(('customerCustom1', customer_custom1))
            
        if customer_custom2 is not None:
            
            _query_params.append(('customerCustom2', customer_custom2))
            
        if customer_custom3 is not None:
            
            _query_params.append(('customerCustom3', customer_custom3))
            
        if customer_custom4 is not None:
            
            _query_params.append(('customerCustom4', customer_custom4))
            
        if customer_custom5 is not None:
            
            _query_params.append(('customerCustom5', customer_custom5))
            
        if page_size is not None:
            
            _query_params.append(('pageSize', page_size))
            
        if page_number is not None:
            
            _query_params.append(('pageNumber', page_number))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter




        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v{apiVersion}/devices',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


