# coding: utf-8

"""
    Cisco IoT Control Center API

    A Python client for the Cisco IoT Control Center (Jasper) REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from jasperclient.models.send_sms_messages_request_callback_param import SendSmsMessagesRequestCallbackParam
from typing import Optional, Set
from typing_extensions import Self

class SendSmsMessagesRequest(BaseModel):
    """
    SendSmsMessagesRequest
    """ # noqa: E501
    message_text: Optional[StrictStr] = Field(default=None, alias="messageText")
    message_encoding: Optional[StrictStr] = Field(default=None, alias="messageEncoding")
    data_coding: Optional[StrictInt] = Field(default=None, alias="dataCoding")
    tpvp: Optional[StrictInt] = None
    callback_param: Optional[SendSmsMessagesRequestCallbackParam] = Field(default=None, alias="callbackParam")
    __properties: ClassVar[List[str]] = ["messageText", "messageEncoding", "dataCoding", "tpvp", "callbackParam"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendSmsMessagesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of callback_param
        if self.callback_param:
            _dict['callbackParam'] = self.callback_param.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendSmsMessagesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "messageText": obj.get("messageText"),
            "messageEncoding": obj.get("messageEncoding"),
            "dataCoding": obj.get("dataCoding"),
            "tpvp": obj.get("tpvp"),
            "callbackParam": SendSmsMessagesRequestCallbackParam.from_dict(obj["callbackParam"]) if obj.get("callbackParam") is not None else None
        })
        return _obj


